spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: secret
    url: jdbc:mysql://localhost:3306/neo_service?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&jdbcCompliantTruncation=false

jwt:
  token:
    expire:
      day:
        due: 8
  secret: neo
security:
  encryption:
    key: neo-encryption_symetric_key