server:
  port: 9082
spring:
  datasource:
    url: jdbc:h2:mem:testdb

    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect