version: "2"
services:
#  neo-user-service:
#    container_name: neo-user-service
#    build: ..
#    ports:
#      - "9082:9082"
  mysql:
    container_name: mysqldb
    build: mysql/
    ports:
      - 3306:3306