version: "3"
services:
#  neo-user-service:
#    container_name: neo-user-service
#    build: ..
#    ports:
#      - "9082:9082"
  mysql:
    container_name: mysqldb
    image: mysql:5.7.24
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456